/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/contacts/breadcrumb.vue')['default']
    Cards: typeof import('./src/components/contacts/cards.vue')['default']
    Feedback: typeof import('./src/components/contacts/feedback.vue')['default']
    Footer: typeof import('./src/components/app/footer.vue')['default']
    FooterCompany: typeof import('./src/components/app/footer-company.vue')['default']
    FooterContacts: typeof import('./src/components/app/footer-contacts.vue')['default']
    FooterMenu: typeof import('./src/components/app/footer-menu.vue')['default']
    FooterPartners: typeof import('./src/components/app/footer-partners.vue')['default']
    FooterRating: typeof import('./src/components/app/footer-rating.vue')['default']
    FooterSocials: typeof import('./src/components/app/footer-socials.vue')['default']
    FooterSubscribe: typeof import('./src/components/app/footer-subscribe.vue')['default']
    Header: typeof import('./src/components/app/header.vue')['default']
    HeaderMenu: typeof import('./src/components/app/header-menu.vue')['default']
    Logo: typeof import('./src/components/app/logo.vue')['default']
    Route: typeof import('./src/components/contacts/route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubHeader: typeof import('./src/components/app/sub-header.vue')['default']
    SubHeaderMenu: typeof import('./src/components/app/sub-header-menu.vue')['default']
    Title: typeof import('./src/components/contacts/title.vue')['default']
  }
}
