/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AInput: typeof import('ant-design-vue/es')['Input']
    NodeIndexOutlined: typeof import('@ant-design/icons-vue')['NodeIndexOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
